import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // App
    'app.name': 'Non Stop',
    'app.tagline': 'أعمالك لا تتوقف',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.signupSuccess': 'تم إنشاء الحساب بنجاح',
    'auth.loginError': 'خطأ في تسجيل الدخول',
    'auth.signupError': 'خطأ في إنشاء الحساب',
    'auth.welcome': 'مرحباً بك في Non Stop',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.createAccount': 'أنشئ حسابك الآن',
    'auth.companyName': 'اسم الشركة',
    'auth.superAdminAccess': 'دخول المدير العام',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.myTasks': 'مهامي اليوم',
    'dashboard.allTasks': 'جميع المهام',
    'dashboard.upcomingEvents': 'المواعيد القادمة',
    'dashboard.manualItems': 'البنود اليدوية',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.myAccount': 'حسابي',
    'dashboard.taskDistribution': 'توزيع المهام',
    'dashboard.delayedTasks': 'المهام المتأخرة',
    'dashboard.loadBalance': 'توازن الأحمال',
    'dashboard.alerts': 'التنبيهات',
    'dashboard.teamSettings': 'إعدادات الفريق',
    'dashboard.companyHealth': 'صحة الشركة',
    'dashboard.departmentLoad': 'حمل الأقسام',
    'dashboard.aiInsights': 'رؤى الذكاء الاصطناعي',
    'dashboard.risks': 'المخاطر والتجاوزات',
    'dashboard.companySettings': 'إعدادات الشركة',
    'dashboard.upcomingMeetings': 'الاجتماعات القادمة',
    'dashboard.quickStats': 'إحصائيات سريعة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.welcome': 'مرحباً',
    'dashboard.todayTasks': 'مهام اليوم',
    
    // Roles
    'role.employee': 'موظف',
    'role.admin': 'مدير',
    'role.super_admin': 'مدير عام',
    'role.department_manager': 'مدير قسم',
    'role.sales_staff': 'موظف مبيعات',
    
    // Team Management
    'team.management': 'إدارة الفريق',
    'team.managementDesc': 'إدارة جميع أعضاء الفريق والصلاحيات',
    'team.addUser': 'إضافة مستخدم',
    'team.addEmployee': 'إضافة موظف',
    'team.totalMembers': 'إجمالي الأعضاء',
    'team.admins': 'المديرون',
    'team.employees': 'الموظفون',
    'team.employeesDesc': 'عرض وإدارة موظفي الفريق',
    'team.activeUsers': 'المستخدمون النشطون',
    'team.allMembers': 'جميع الأعضاء',
    'team.name': 'الاسم',
    'team.role': 'الدور',
    'team.department': 'القسم',
    'team.phone': 'الهاتف',
    'team.status': 'الحالة',
    'team.active': 'نشط',
    'team.inactive': 'غير نشط',
    'team.changeRole': 'تغيير الدور',
    'team.changeRoleFor': 'تغيير دور',
    'team.newRole': 'الدور الجديد',
    'team.deactivate': 'إلغاء التفعيل',
    'team.activate': 'تفعيل',
    'team.deleteUser': 'حذف المستخدم',
    'team.deleteUserConfirm': 'هل أنت متأكد من حذف',
    'team.fullName': 'الاسم الكامل',
    'team.fullNameAr': 'الاسم بالعربية',
    'team.selectDepartment': 'اختر القسم',
    'team.userCreated': 'تم إنشاء المستخدم',
    'team.userCreatedDesc': 'تم إنشاء المستخدم بنجاح',
    'team.roleUpdated': 'تم تحديث الدور',
    'team.roleUpdatedDesc': 'تم تحديث دور المستخدم بنجاح',
    'team.statusUpdated': 'تم تحديث الحالة',
    'team.statusUpdatedDesc': 'تم تحديث حالة المستخدم بنجاح',
    'team.userDeleted': 'تم حذف المستخدم',
    'team.userDeletedDesc': 'تم حذف المستخدم بنجاح',
    'team.performance': 'الأداء',
    'team.totalEmployees': 'إجمالي الموظفين',
    'team.activeEmployees': 'الموظفون النشطون',
    'team.employeesList': 'قائمة الموظفين',
    'team.noEmployees': 'لا يوجد موظفون',
    'team.permissions': 'الصلاحيات',
    'team.managePermissions': 'إدارة الصلاحيات',
    
    // Tasks
    'tasks.title': 'المهام',
    'tasks.total': 'الإجمالي',
    'tasks.completed': 'مكتمل',
    'tasks.inProgress': 'قيد التنفيذ',
    'tasks.pending': 'قيد الانتظار',
    'tasks.overdue': 'متأخر',
    'tasks.cancelled': 'ملغي',
    'tasks.new': 'مهمة جديدة',
    'tasks.taskTitle': 'عنوان المهمة',
    'tasks.description': 'الوصف',
    'tasks.priority': 'الأولوية',
    'tasks.assignee': 'المُسند إليه',
    'tasks.dueDate': 'تاريخ الاستحقاق',
    'tasks.status': 'الحالة',
    'tasks.created': 'تم الإنشاء',
    'tasks.updated': 'تم التحديث',
    'tasks.start': 'بدء العمل',
    'tasks.complete': 'إكمال',
    'tasks.reassign': 'إعادة تعيين',
    'tasks.delete': 'حذف',
    'tasks.edit': 'تعديل',
    'tasks.view': 'عرض',
    'tasks.comments': 'التعليقات',
    'tasks.addComment': 'أضف تعليق',
    'tasks.noTasks': 'لا توجد مهام',
    'tasks.filterByStatus': 'تصفية حسب الحالة',
    'tasks.filterByPriority': 'تصفية حسب الأولوية',
    'tasks.searchTasks': 'البحث في المهام',
    'tasks.all': 'الكل',
    
    // Priority
    'priority.low': 'منخفضة',
    'priority.medium': 'متوسطة',
    'priority.high': 'عالية',
    'priority.urgent': 'عاجلة',
    
    // Leads
    'leads.title': 'العملاء المحتملين',
    'leads.new': 'عميل محتمل جديد',
    'leads.name': 'الاسم',
    'leads.email': 'البريد الإلكتروني',
    'leads.phone': 'الهاتف',
    'leads.source': 'المصدر',
    'leads.status': 'الحالة',
    'leads.assignedTo': 'مُسند إلى',
    'leads.notes': 'الملاحظات',
    'leads.followUp': 'المتابعة',
    'leads.noLeads': 'لا يوجد عملاء محتملين',
    'leads.statusNew': 'جديد',
    'leads.statusContacted': 'تم التواصل',
    'leads.statusInterested': 'مهتم',
    'leads.statusNotInterested': 'غير مهتم',
    'leads.statusProposalSent': 'تم إرسال العرض',
    'leads.statusMeetingScheduled': 'تم جدولة اجتماع',
    'leads.statusClosedWon': 'تم الإغلاق - فوز',
    'leads.statusClosedLost': 'تم الإغلاق - خسارة',
    
    // Meetings
    'meetings.title': 'الاجتماعات',
    'meetings.new': 'اجتماع جديد',
    'meetings.meetingTitle': 'عنوان الاجتماع',
    'meetings.description': 'الوصف',
    'meetings.startTime': 'وقت البداية',
    'meetings.endTime': 'وقت النهاية',
    'meetings.location': 'المكان',
    'meetings.participants': 'المشاركون',
    'meetings.agenda': 'جدول الأعمال',
    'meetings.decisions': 'القرارات',
    'meetings.followUpTasks': 'مهام المتابعة',
    'meetings.noMeetings': 'لا توجد اجتماعات',
    'meetings.scheduled': 'مجدولة',
    'meetings.inProgress': 'جارية',
    'meetings.completed': 'مكتملة',
    'meetings.cancelled': 'ملغاة',
    'meetings.type': 'نوع الاجتماع',
    'meetings.general': 'عام',
    'meetings.client': 'عميل',
    'meetings.internal': 'داخلي',
    'meetings.review': 'مراجعة',
    
    // Chat
    'chat.title': 'الدردشة',
    'chat.newMessage': 'رسالة جديدة',
    'chat.typeMessage': 'اكتب رسالة...',
    'chat.send': 'إرسال',
    'chat.noMessages': 'لا توجد رسائل',
    'chat.rooms': 'الغرف',
    'chat.newRoom': 'غرفة جديدة',
    
    // Clients
    'clients.title': 'العملاء',
    'clients.new': 'عميل جديد',
    'clients.noClients': 'لا يوجد عملاء',
    
    // Contracts
    'contracts.title': 'العقود',
    'contracts.new': 'عقد جديد',
    'contracts.noContracts': 'لا توجد عقود',
    
    // Departments
    'departments.title': 'الأقسام',
    'departments.new': 'قسم جديد',
    'departments.noDepartments': 'لا توجد أقسام',
    'departments.operations': 'العمليات',
    'departments.marketing': 'التسويق',
    'departments.hr': 'الموارد البشرية',
    'departments.finance': 'المالية',
    'departments.it': 'تقنية المعلومات',
    'departments.sales': 'المبيعات',
    'departments.legal': 'القانونية',
    'departments.other': 'أخرى',
    'departments.design': 'التصميم',
    'departments.content': 'المحتوى',
    'departments.social_media': 'التواصل الاجتماعي',
    'departments.video': 'الفيديو',
    
    // AI Insights
    'ai.title': 'رؤى الذكاء الاصطناعي',
    'ai.analyze': 'تحليل',
    'ai.suggestions': 'اقتراحات',
    'ai.risks': 'المخاطر',
    'ai.performance': 'الأداء',
    'ai.workload': 'حمل العمل',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.markAllRead': 'قراءة الكل',
    'notifications.noNotifications': 'لا توجد إشعارات',
    'notifications.urgent': 'عاجل',
    'notifications.urgentCall': 'مكالمة عاجلة',
    'notifications.sendUrgentCall': 'إرسال مكالمة عاجلة',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.company': 'الشركة',
    'settings.branding': 'العلامة التجارية',
    'settings.employees': 'الموظفين',
    'settings.permissions': 'الصلاحيات',
    'settings.security': 'الأمان',
    
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.tasks': 'المهام',
    'nav.leads': 'العملاء المحتملين',
    'nav.meetings': 'الاجتماعات',
    'nav.chat': 'الدردشة',
    'nav.clients': 'العملاء',
    'nav.contracts': 'العقود',
    'nav.departments': 'الأقسام',
    'nav.aiInsights': 'رؤى AI',
    'nav.settings': 'الإعدادات',
    'nav.events': 'الأحداث',
    'nav.manual': 'العناصر اليدوية',
    'nav.account': 'حسابي',
    'nav.employees': 'الموظفين',
    'nav.teamManagement': 'إدارة الفريق',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.settings': 'الإعدادات',
    'common.profile': 'الملف الشخصي',
    'common.language': 'اللغة',
    'common.theme': 'المظهر',
    'common.dark': 'داكن',
    'common.light': 'فاتح',
    'common.actions': 'الإجراءات',
    'common.viewAll': 'عرض الكل',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.or': 'أو',
    'common.and': 'و',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.today': 'اليوم',
    'common.tomorrow': 'غداً',
    'common.yesterday': 'أمس',
    'common.now': 'الآن',
    'common.soon': 'قريباً',
    'common.inMinutes': 'خلال {count} دقيقة',
  },
  en: {
    // App
    'app.name': 'Non Stop',
    'app.tagline': 'Your Work Never Stops',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.loginSuccess': 'Login successful',
    'auth.signupSuccess': 'Account created successfully',
    'auth.loginError': 'Login error',
    'auth.signupError': 'Signup error',
    'auth.welcome': 'Welcome to Non Stop',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create your account',
    'auth.companyName': 'Company Name',
    'auth.superAdminAccess': 'Super Admin Access',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.myTasks': 'My Tasks Today',
    'dashboard.allTasks': 'All Tasks',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.manualItems': 'Manual Items',
    'dashboard.notifications': 'Notifications',
    'dashboard.myAccount': 'My Account',
    'dashboard.taskDistribution': 'Task Distribution',
    'dashboard.delayedTasks': 'Delayed Tasks',
    'dashboard.loadBalance': 'Load Balance',
    'dashboard.alerts': 'Alerts',
    'dashboard.teamSettings': 'Team Settings',
    'dashboard.companyHealth': 'Company Health',
    'dashboard.departmentLoad': 'Department Load',
    'dashboard.aiInsights': 'AI Insights',
    'dashboard.risks': 'Risks & Violations',
    'dashboard.companySettings': 'Company Settings',
    'dashboard.upcomingMeetings': 'Upcoming Meetings',
    'dashboard.quickStats': 'Quick Stats',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.welcome': 'Welcome',
    'dashboard.todayTasks': 'Today\'s Tasks',
    
    // Roles
    'role.employee': 'Employee',
    'role.admin': 'Admin',
    'role.super_admin': 'Super Admin',
    'role.department_manager': 'Department Manager',
    'role.sales_staff': 'Sales Staff',
    
    // Team Management
    'team.management': 'Team Management',
    'team.managementDesc': 'Manage all team members and permissions',
    'team.addUser': 'Add User',
    'team.addEmployee': 'Add Employee',
    'team.totalMembers': 'Total Members',
    'team.admins': 'Admins',
    'team.employees': 'Employees',
    'team.employeesDesc': 'View and manage team employees',
    'team.activeUsers': 'Active Users',
    'team.allMembers': 'All Members',
    'team.name': 'Name',
    'team.role': 'Role',
    'team.department': 'Department',
    'team.phone': 'Phone',
    'team.status': 'Status',
    'team.active': 'Active',
    'team.inactive': 'Inactive',
    'team.changeRole': 'Change Role',
    'team.changeRoleFor': 'Change role for',
    'team.newRole': 'New Role',
    'team.deactivate': 'Deactivate',
    'team.activate': 'Activate',
    'team.deleteUser': 'Delete User',
    'team.deleteUserConfirm': 'Are you sure you want to delete',
    'team.fullName': 'Full Name',
    'team.fullNameAr': 'Arabic Name',
    'team.selectDepartment': 'Select Department',
    'team.userCreated': 'User Created',
    'team.userCreatedDesc': 'User created successfully',
    'team.roleUpdated': 'Role Updated',
    'team.roleUpdatedDesc': 'User role updated successfully',
    'team.statusUpdated': 'Status Updated',
    'team.statusUpdatedDesc': 'User status updated successfully',
    'team.userDeleted': 'User Deleted',
    'team.userDeletedDesc': 'User deleted successfully',
    'team.performance': 'Performance',
    'team.totalEmployees': 'Total Employees',
    'team.activeEmployees': 'Active Employees',
    'team.employeesList': 'Employees List',
    'team.noEmployees': 'No employees',
    'team.permissions': 'Permissions',
    'team.managePermissions': 'Manage Permissions',
    
    // Tasks
    'tasks.title': 'Tasks',
    'tasks.total': 'Total',
    'tasks.completed': 'Completed',
    'tasks.inProgress': 'In Progress',
    'tasks.pending': 'Pending',
    'tasks.overdue': 'Overdue',
    'tasks.cancelled': 'Cancelled',
    'tasks.new': 'New Task',
    'tasks.taskTitle': 'Task Title',
    'tasks.description': 'Description',
    'tasks.priority': 'Priority',
    'tasks.assignee': 'Assignee',
    'tasks.dueDate': 'Due Date',
    'tasks.status': 'Status',
    'tasks.created': 'Created',
    'tasks.updated': 'Updated',
    'tasks.start': 'Start Work',
    'tasks.complete': 'Complete',
    'tasks.reassign': 'Reassign',
    'tasks.delete': 'Delete',
    'tasks.edit': 'Edit',
    'tasks.view': 'View',
    'tasks.comments': 'Comments',
    'tasks.addComment': 'Add Comment',
    'tasks.noTasks': 'No tasks',
    'tasks.filterByStatus': 'Filter by status',
    'tasks.filterByPriority': 'Filter by priority',
    'tasks.searchTasks': 'Search tasks',
    'tasks.all': 'All',
    
    // Priority
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',
    
    // Leads
    'leads.title': 'Leads',
    'leads.new': 'New Lead',
    'leads.name': 'Name',
    'leads.email': 'Email',
    'leads.phone': 'Phone',
    'leads.source': 'Source',
    'leads.status': 'Status',
    'leads.assignedTo': 'Assigned To',
    'leads.notes': 'Notes',
    'leads.followUp': 'Follow Up',
    'leads.noLeads': 'No leads',
    'leads.statusNew': 'New',
    'leads.statusContacted': 'Contacted',
    'leads.statusInterested': 'Interested',
    'leads.statusNotInterested': 'Not Interested',
    'leads.statusProposalSent': 'Proposal Sent',
    'leads.statusMeetingScheduled': 'Meeting Scheduled',
    'leads.statusClosedWon': 'Closed Won',
    'leads.statusClosedLost': 'Closed Lost',
    
    // Meetings
    'meetings.title': 'Meetings',
    'meetings.new': 'New Meeting',
    'meetings.meetingTitle': 'Meeting Title',
    'meetings.description': 'Description',
    'meetings.startTime': 'Start Time',
    'meetings.endTime': 'End Time',
    'meetings.location': 'Location',
    'meetings.participants': 'Participants',
    'meetings.agenda': 'Agenda',
    'meetings.decisions': 'Decisions',
    'meetings.followUpTasks': 'Follow-up Tasks',
    'meetings.noMeetings': 'No meetings',
    'meetings.scheduled': 'Scheduled',
    'meetings.inProgress': 'In Progress',
    'meetings.completed': 'Completed',
    'meetings.cancelled': 'Cancelled',
    'meetings.type': 'Meeting Type',
    'meetings.general': 'General',
    'meetings.client': 'Client',
    'meetings.internal': 'Internal',
    'meetings.review': 'Review',
    
    // Chat
    'chat.title': 'Chat',
    'chat.newMessage': 'New Message',
    'chat.typeMessage': 'Type a message...',
    'chat.send': 'Send',
    'chat.noMessages': 'No messages',
    'chat.rooms': 'Rooms',
    'chat.newRoom': 'New Room',
    
    // Clients
    'clients.title': 'Clients',
    'clients.new': 'New Client',
    'clients.noClients': 'No clients',
    
    // Contracts
    'contracts.title': 'Contracts',
    'contracts.new': 'New Contract',
    'contracts.noContracts': 'No contracts',
    
    // Departments
    'departments.title': 'Departments',
    'departments.new': 'New Department',
    'departments.noDepartments': 'No departments',
    'departments.operations': 'Operations',
    'departments.marketing': 'Marketing',
    'departments.hr': 'Human Resources',
    'departments.finance': 'Finance',
    'departments.it': 'IT',
    'departments.sales': 'Sales',
    'departments.legal': 'Legal',
    'departments.other': 'Other',
    'departments.design': 'Design',
    'departments.content': 'Content',
    'departments.social_media': 'Social Media',
    'departments.video': 'Video',
    
    // AI Insights
    'ai.title': 'AI Insights',
    'ai.analyze': 'Analyze',
    'ai.suggestions': 'Suggestions',
    'ai.risks': 'Risks',
    'ai.performance': 'Performance',
    'ai.workload': 'Workload',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all read',
    'notifications.noNotifications': 'No notifications',
    'notifications.urgent': 'Urgent',
    'notifications.urgentCall': 'Urgent Call',
    'notifications.sendUrgentCall': 'Send Urgent Call',
    
    // Settings
    'settings.title': 'Settings',
    'settings.company': 'Company',
    'settings.branding': 'Branding',
    'settings.employees': 'Employees',
    'settings.permissions': 'Permissions',
    'settings.security': 'Security',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tasks': 'Tasks',
    'nav.leads': 'Leads',
    'nav.meetings': 'Meetings',
    'nav.chat': 'Chat',
    'nav.clients': 'Clients',
    'nav.contracts': 'Contracts',
    'nav.departments': 'Departments',
    'nav.aiInsights': 'AI Insights',
    'nav.settings': 'Settings',
    'nav.events': 'Events',
    'nav.manual': 'Manual Items',
    'nav.account': 'My Account',
    'nav.employees': 'Employees',
    'nav.teamManagement': 'Team Management',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.noData': 'No data',
    'common.error': 'Error occurred',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.dark': 'Dark',
    'common.light': 'Light',
    'common.actions': 'Actions',
    'common.viewAll': 'View All',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',
    'common.from': 'From',
    'common.to': 'To',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.now': 'Now',
    'common.soon': 'Soon',
    'common.inMinutes': 'In {count} minutes',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('nonstop-language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nonstop-language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
